# Este es el formato para tu archivo .streamlit/secrets.toml
# ¡Importante! Usa la URL EXTERNA y añade ?sslmode=require al final.

DATABASE_URL="postgresql://thebadgers_user:NcO467HxHkGrSF9WI4GEOtlveoNbpBlf@dpg-d11jvlggjchc7383na7g-a.oregon-postgres.render.com/thebadgers?sslmode=require"
